INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Major,15', 'Tarragona', 'Oscars',43100);

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Major,25', 'Tarragona', 'JCS',43100);

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Major,35', 'Tarragona', 'YELMUS',43100);



INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',100,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',100,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',100,1);


INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',100,2);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',100,2);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',100,2);


INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',100,3);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',100,3);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',100,3);


INSERT INTO SEAT(NUMBER,SEAT_ROW,X,Y,TYPE,ACTIVE,ROOM_ID) VALUES (1,'A',0,0,'STANDARD',true,1);
INSERT INTO SEAT(NUMBER,SEAT_ROW,X,Y,TYPE,ACTIVE,ROOM_ID) VALUES (2,'A',1,0,'STANDARD',true,1);
INSERT INTO SEAT(NUMBER,SEAT_ROW,X,Y,TYPE,ACTIVE,ROOM_ID) VALUES (3,'A',2,0,'STANDARD',true,1);
INSERT INTO SEAT(NUMBER,SEAT_ROW,X,Y,TYPE,ACTIVE,ROOM_ID) VALUES (4,'B',0,1,'STANDARD',true,1);
INSERT INTO SEAT(NUMBER,SEAT_ROW,X,Y,TYPE,ACTIVE,ROOM_ID) VALUES (5,'B',1,1,'STANDARD',true,1);
INSERT INTO SEAT(NUMBER,SEAT_ROW,X,Y,TYPE,ACTIVE,ROOM_ID) VALUES (6,'B',2,1,'STANDARD',true,1);


INSERT INTO SEAT(NUMBER,SEAT_ROW,X,Y,TYPE,ACTIVE,ROOM_ID) VALUES (1,'A',0,0,'STANDARD',true,2);
INSERT INTO SEAT(NUMBER,SEAT_ROW,X,Y,TYPE,ACTIVE,ROOM_ID) VALUES (2,'A',1,0,'STANDARD',true,2);
INSERT INTO SEAT(NUMBER,SEAT_ROW,X,Y,TYPE,ACTIVE,ROOM_ID) VALUES (3,'B',0,1,'STANDARD',true,2);

