INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Major,15', 'Tarragona', 'Oscars',43100);

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Major,25', 'Tarragona', 'JCS',43100);

INSERT INTO CINEMA(ADDRESS,CITY,NAME,POSTAL_CODE) VALUES
('Major,35', 'Tarragona', 'YELMUS',43100);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 1',100,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 2',150,1);

INSERT INTO ROOM(NAME,CAPACITY,CINEMA_ID) VALUES
('Sala 3',200,1);


